gravity_compensation_controller:
  type: open_manipulator_controllers/GravityCompensationController
  joint_names:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  root_link: world
  tip_link: camera_link
